# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgsOpenScope
                                 A QGIS plugin
 A collection of tools for the openScope project

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-09-13
        git sha              : $Format:%H$
        copyright            : (C) 2019 by openScope
        email                : 3430117+oobayly@users.noreply.github.com

 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QApplication, QFileDialog, QMessageBox
from qgis.core import QgsProject

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .QgsOpenScope_dialog import QgsOpenScopeDialog
import os.path
import json
import processing
from qgis.core import QgsProject, QgsVectorFileWriter
from .OpenScope.AirspaceModel import AirspaceModel
from .OpenScope.FixModel import FixModel
from .OpenScope.MapModel import MapModel
from .OpenScope.RestrictedModel import RestrictedModel

class QgsOpenScope:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'QgsOpenScope_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&QgsOpenScope')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('QgsOpenScope', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/QgsOpenScope/icon.png'
        self.add_action(
            None,
            text=self.tr(u'Load Airport'),
            callback=self.run,
            parent=self.iface.mainWindow(),
            add_to_toolbar=False
        )
        self.add_action(
            None,
            text='Export Airspace',
            callback=self.exportAirspace,
            parent=self.iface.mainWindow(),
            add_to_toolbar=False
        )
        self.add_action(
            None,
            text='Export Fixes',
            callback=self.exportFixes,
            parent=self.iface.mainWindow(),
            add_to_toolbar=False
        )
        self.add_action(
            None,
            text='Export Maps',
            callback=self.exportMaps,
            parent=self.iface.mainWindow(),
            add_to_toolbar=False
        )
        self.add_action(
            None,
            text='Export Restricted',
            callback=self.exportRestricted,
            parent=self.iface.mainWindow(),
            add_to_toolbar=False
        )
        self.add_action(
            None,
            text='Export Terrain',
            callback=self.exportTerrain,
            parent=self.iface.mainWindow(),
            add_to_toolbar=False
        )

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&QgsOpenScope'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = QgsOpenScopeDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass


    def copyToClipboard(self, text):
        cb = QApplication.clipboard()
        cb.clear(mode=cb.Clipboard )
        cb.setText(text, mode=cb.Clipboard)        

    def exportAirspace(self):
        root = self.iface.layerTreeView()
        airspaces = QgsProject.instance().mapLayersByName('Airspace')

        if len(airspaces) == 0:
            QMessageBox.information(None, 'QgsOpenScope', 'Couldn\'t find a \'Airspace\' layer.')
            return

        self.copyToClipboard(AirspaceModel.export(airspaces[0]))
        QMessageBox.information(None, 'QgsOpenScope', 'Airspace JSON has been copied to the clipboard.')

    def exportFixes(self):
        root = self.iface.layerTreeView()
        fixes = QgsProject.instance().mapLayersByName('Fixes')

        if len(fixes) == 0:
            QMessageBox.information(None, 'QgsOpenScope', 'Couldn\'t find a \'Fixes\' layer.')
            return

        self.copyToClipboard(FixModel.export(fixes[0]))
        QMessageBox.information(None, 'QgsOpenScope', 'Fixes JSON has been copied to the clipboard.')

    def exportRestricted(self):
        root = self.iface.layerTreeView()
        restricted = QgsProject.instance().mapLayersByName('Restricted')

        if len(restricted) == 0:
            QMessageBox.information(None, 'QgsOpenScope', 'Couldn\'t find a \'Restricted\' layer.')
            return

        self.copyToClipboard(RestrictedModel.export(restricted[0]))
        QMessageBox.information(None, 'QgsOpenScope', 'Restricted Airspace JSON has been copied to the clipboard.')

    def exportMaps(self):
        mapsGroup = QgsProject.instance().layerTreeRoot().findGroup('Maps')

        if not mapsGroup:
            QMessageBox.information(None, 'QgsOpenScope', 'Couldn\'t find any Map layers.')
            return

        layers = list(map(lambda x : x.layer(), mapsGroup.children()))

        self.copyToClipboard(MapModel.export(layers))
        QMessageBox.information(None, 'QgsOpenScope', 'Map JSON has been copied to the clipboard.')

    def exportTerrain(self):
        selected = self.iface.layerTreeView().selectedLayers()

        if len(selected) == 0:
            QMessageBox.information(None, 'QgsOpenScope', 'At least one terrain layer must be selected for export.')
            return
        
        for layer in selected:
            if layer.fields().indexFromName('elevation') == -1:
                QMessageBox.information(None, 'QgsOpenScope', 'The \'%s\' layer doesn\'t have an elevation attribute.' % layer.name())
                return
        
        fileName, _ = QFileDialog.getSaveFileName(None, 'Save openScope terrain', '', 'Terrain Files (*.geojson)')
        if not fileName:
            return

        result = processing.run('qgis:mergevectorlayers', {
            'LAYERS': selected,
            'OUTPUT': 'memory:'
        })
        merged = result['OUTPUT']
        merged.setName('Terrain - Merged')

        QgsVectorFileWriter.writeAsVectorFormat(
            merged,
            fileName,
            'utf-8',
            merged.crs(),
            'GeoJson',
            attributes = [
                merged.fields().indexFromName('elevation') # Only the elevation layer
            ],
            layerOptions = [
                'COORDINATE_PRECISION=10'
            ]
        )
